### ISSUE TITLE
Azure DevOps pulumi preview command failing (C# stack) due to nuget null HOME ENV variable 

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [pulumi/pulumi-az-pipelines-task#20] opened 2019-11-13 13:59 UTC
i know C# language support still in preview. 

I have observed c# stack project failing on DevOps
error : Value cannot be null. (Parameter 'path1')

![image](https://user-images.githubusercontent.com/16232384/68770107-2554f680-05eb-11ea-8189-294c74671aaf.png)

![image](https://user-images.githubusercontent.com/16232384/68770125-33a31280-05eb-11ea-8310-fbb55d62a98d.png)

But i am able to do dotnet build on the project, but pulumi preview command failing
![image](https://user-images.githubusercontent.com/16232384/68770255-6cdb8280-05eb-11ea-8aa2-6b2d7371d319.png)

Also dotnet restore command also working fine. is there any switch i can pass to pulumi CLI not to restore nugets because nugets already restored (like dotnet build --no-restore

**Comment by praneetloke** [comment] 2019-11-13 21:40
@rajeshmuraleedharan it is not clear to me if you are using this Pulumi task extension to run your Pulumi app in Azure DevOps? Are you manually installing the Pulumi CLI yourself and then running into an issue with running `pulumi preview`?

**Comment by rajeshmuraleedharan** [comment] 2019-11-14 04:02
Yes i am using Pulumi task extension to run c# pulumi app. I have installed pulumi sdk on my deployment agent (windows server 2016). Which has .net core 3 sdk pre-installed. if i run dotnet restore/ build as a deployment step then project getting build successfully. pulumi preview/ up getting above error

**Comment by praneetloke** [comment] 2019-11-14 05:33
@rajeshmuraleedharan thanks for clarifying. Can you please post your Azure Pipelines config in a GitHub Gist? (Be sure to remove any confidential information from it.)

**Comment by praneetloke** [comment] 2019-11-14 08:07
A new version of the task extension was released which potentially fixes this issue. Would you mind giving it a try? The extension version is 1.0.1. Your build agent should automatically pick-up the new version so as long as you are using the major version 1.x of the task extension.

**Comment by praneetloke** [comment] 2019-11-20 06:51
@rajeshmuraleedharan I am going to close this issue as I think the issue is fixed by #25. Please feel free to reopen this if you are still having issues.

**Closed by praneetloke** 2019-11-20 06:51 UTC
Labels: question
