### ISSUE TITLE
Cannot use the task with pulumi version 3.37.0

### ISSUE THREAD

**Issue by sinePaul** [pulumi/pulumi-az-pipelines-task#109] opened 2022-07-27 15:38 UTC
**Describe the bug**
This task download the latest version of pulumi and install it. The new version 3.37.0 will cause the installation script to fail when installing pulumi 

**To Reproduce**
1. Use that task without specifying a specific version of pulumi

**Expected behavior**
Pulumi to be installed

**Screenshots**
##[debug]Exit code 0 received from tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]STDIO streams have closed for tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]Agent.Version=2.206.1
##[debug]task result: Failed
##[error]Pulumi installation failed with error 'Directory does not exist: C:\a\_temp\c9d3b717-c67c-4742-846f-47d9c98df9c1\pulumi\bin'.

**Additional context**
I managed to use the task by specifying the version 3.36.0 on the pulumi task

**Comment by AaronFriel** [comment] 2022-07-27 18:22
Likely a duplicate of https://github.com/pulumi/pulumi/issues/10262

We'll track this there as a P0.

**Comment by AaronFriel** [comment] 2022-07-27 19:45
@sinePaul @MitchellGerdisch could you confirm that setting 3.36.0 as the Pulumi version allows pipelines to resume?

This workaround should work while we release 3.37.1.

**Comment by AaronFriel** [comment] 2022-07-28 17:06
This is resolved with the release of 3.37.1 yesterday.

Thank you very much for reporting and apologies for any disruption.

**Closed by AaronFriel** 2022-07-28 17:06 UTC
Labels: resolution/fixed, kind/bug, p0, impact/regression

**Comment by sinePaul** [comment] 2022-07-29 08:13
> This is resolved with the release of 3.37.1 yesterday.
> 
> Thank you very much for reporting and apologies for any disruption.

Thanks!
