### ISSUE TITLE
Pulumi access token not always honoured in scaleset

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-az-pipelines-task#111] opened 2022-08-18 17:58 UTC
When running azure devops runners as an Azure scaleset, if the azure scaleset has an env var set for a pulumi access token, the pipeline token isn't always honoured.

Will try and get a repro for this

**Comment by RobbieMcKinstry** [comment] 2022-08-30 15:22
Hey there @jaxxstorm ! I just wanted to nudge you for a repro on this issue.

**Comment by praneetloke** [comment] 2022-09-08 22:07
I don't know if self-hosted runners will propagate the scaleset's env vars to pipeline tasks. Pipeline tasks might just not inherit them by default. This might actually be a question for the Azure Pipelines team.

**Comment by lukehoban** [comment] 2022-10-17 20:49
Closing out for now - since it seems both no repro and by design - but feel free to reopen if there's more details and a clear indication that this is something that can be solved in the Pulumi Pipelines Task.

**Closed by lukehoban** 2022-10-17 20:49 UTC
Labels: size/S, kind/bug, needs-repro, resolution/no-repro, impact/usability, awaiting-feedback
