### ISSUE TITLE
Task Fails when using a Management Group scoped Service Connection

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-az-pipelines-task#122] opened 2022-11-10 15:02 UTC
**Describe the bug**
When using the task, the task goes and grabs the subscriptionid off of the passed in service connection via getEndpointDataParameter. If using a management group scoped service connection the subscriptionid does not exist on the service connections metadata so it causes it to throw an error and the task to fail.

**To Reproduce**
Pass in a management group scoped service connection as the azureSubscription parameter for the task. The task will fail.

**Expected behavior**
Expect the task to continue to run pulumi as expected as the azure subscription can be provided in the stack yaml for the provider.

**Comment by aq17** [comment] 2022-11-14 21:34
Hi @zbuchheit , thanks for opening this issue – would you be able to provide a code snippet/ example so we can try to reproduce this?

**Comment by phillipedwards** [comment] 2022-11-15 21:42
@aq17 This ask is related to [this](https://github.com/pulumi/pulumi-az-pipelines-task/blob/ad15dfc126dbe808888044eea139ee71ccb9e424/buildAndReleaseTask/serviceEndpoint.ts#L34-L38) code block. Specifically, a management group scoped service connection does not have a single `subscriptionId` (it can have multiple).  

The problem becomes `subscriptionId` is marked as required so, if a `subscriptionId` is not present in the ADO task, an error occurs.

**Comment by phillipedwards** [comment] 2022-11-15 21:44
What I'm proposing is we set the `subscriptionId` to optional so instead of:

```typescript
subscriptionId: tl.getEndpointDataParameter(
            connectedServiceName,
            "subscriptionid",
            false // optional == false
        ),
```

we end up with:
```typescript
subscriptionId: tl.getEndpointDataParameter(
            connectedServiceName,
            "subscriptionid",
            true // optional == true
        ),
```

**Comment by aq17** [comment] 2022-11-15 21:46
Thanks for clarifying @phillipedwards , that makes sense. Would you like to open a PR or shall I?

**Comment by phillipedwards** [comment] 2022-11-15 22:01
@aq17  PR is up, although it looks like some CI failures are occurring... 
https://github.com/pulumi/pulumi-az-pipelines-task/pull/123

**Comment by aq17** [comment] 2022-11-15 22:25
@phillipedwards on second glance it looks like a subscription ID is required (https://arinco.com.au/blog/azure-done-right-series-azure-devops-and-management-group-service-connections/) – need to find a way to resolve this when a mgmt group is used

**Comment by phillipedwards** [comment] 2022-11-15 22:32
I think for this particular case `subscriptionId` is required due to the fact the task is directly using the data point, however, I don't think (could be wrong) it should be required with the Pulumi ADO task. Ultimately, the `subscriptionId` will have to be specified in a Pulumi stack configuration, if a customer wants to use Management Group Service Connection and we will have to make that known.

**Comment by phillipedwards** [comment] 2022-11-16 19:38
@aq17 can you take a look and approve if we're good to go?

**Comment by aq17** [comment] 2022-11-16 20:03
@phillipedwards CI is still failing likely due to the `subscriptionId` requirement to establish the service endpoint. The link above ^ uses a PowerShell script to select a subscription from the management group

**Closed** 2022-11-28 22:56 UTC
Labels: impact/usability
